--------------------------------------------------------
--  파일이 생성됨 - 화요일-11월-09-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTE
--------------------------------------------------------

  CREATE TABLE "BCLASS"."NOTE" 
   (	"NO" NUMBER, 
	"SEND_NICK" VARCHAR2(50 BYTE), 
	"RECV_NICK" VARCHAR2(50 BYTE), 
	"SEND_TIME" DATE DEFAULT sysdate, 
	"CONTENT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BCLASS.NOTE
SET DEFINE OFF;
Insert into BCLASS.NOTE (NO,SEND_NICK,RECV_NICK,SEND_TIME,CONTENT) values (3,'정우','선민',to_date('21/11/09','RR/MM/DD'),'ㅎㅇ');
Insert into BCLASS.NOTE (NO,SEND_NICK,RECV_NICK,SEND_TIME,CONTENT) values (1,'선민','정우',to_date('21/11/09','RR/MM/DD'),'gd');
Insert into BCLASS.NOTE (NO,SEND_NICK,RECV_NICK,SEND_TIME,CONTENT) values (2,'선민','정우',to_date('21/11/09','RR/MM/DD'),'하이루');
--------------------------------------------------------
--  DDL for Index SYS_C007507
--------------------------------------------------------

  CREATE UNIQUE INDEX "BCLASS"."SYS_C007507" ON "BCLASS"."NOTE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTE
--------------------------------------------------------

  ALTER TABLE "BCLASS"."NOTE" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BCLASS"."NOTE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BCLASS"."NOTE" MODIFY ("SEND_TIME" NOT NULL ENABLE);
  ALTER TABLE "BCLASS"."NOTE" MODIFY ("RECV_NICK" NOT NULL ENABLE);
  ALTER TABLE "BCLASS"."NOTE" MODIFY ("SEND_NICK" NOT NULL ENABLE);
  ALTER TABLE "BCLASS"."NOTE" MODIFY ("NO" NOT NULL ENABLE);
